# Generated by Django 2.2.4 on 2019-08-24 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reqT',
            fields=[
                ('request_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('req', models.CharField(max_length=30)),
            ],
        ),
    ]
