# Generated by Django 2.2.4 on 2019-08-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='allReqs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_id', models.CharField(max_length=10)),
                ('NID', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('complete', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='req1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_id', models.CharField(max_length=10)),
                ('NID', models.CharField(max_length=10)),
                ('ltype', models.IntegerField()),
                ('complete', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
