# Generated by Django 2.2.4 on 2019-08-24 05:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('req', '0002_allreqs_req1'),
    ]

    operations = [
        migrations.AddField(
            model_name='allreqs',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='allreqs',
            name='expDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='req1',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='req1',
            name='expDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
