# Generated by Django 2.2.4 on 2019-08-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req', '0003_auto_20190824_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='req1',
            name='NID2',
            field=models.CharField(default=1234567890, max_length=10),
            preserve_default=False,
        ),
    ]
