# Generated by Django 2.2.4 on 2019-08-24 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('req', '0004_req1_nid2'),
    ]

    operations = [
        migrations.AddField(
            model_name='allreqs',
            name='reqtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='req.reqT'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='req1',
            name='reqtype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='req.reqT'),
            preserve_default=False,
        ),
    ]
