# Generated by Django 2.2.4 on 2019-08-24 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('req', '0005_auto_20190824_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allreqs',
            name='reqtype',
        ),
        migrations.RemoveField(
            model_name='req1',
            name='reqtype',
        ),
    ]
