# Generated by Django 2.2.4 on 2019-08-24 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('req', '0007_auto_20190824_0529'),
    ]

    operations = [
        migrations.CreateModel(
            name='req2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_id', models.CharField(max_length=10)),
                ('NID', models.CharField(max_length=10)),
                ('lNo', models.IntegerField()),
                ('complete', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
                ('expDate', models.DateTimeField()),
                ('reqtype', models.IntegerField()),
                ('delivery', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
            ],
        ),
    ]
