# Generated by Django 2.2.4 on 2019-08-24 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('req', '0009_req11_req3_req4_req5_req6_req7'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='req11',
            name='address',
        ),
        migrations.RemoveField(
            model_name='req11',
            name='delivery',
        ),
    ]
