# Generated by Django 2.2.4 on 2019-08-15 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('fullname', models.CharField(max_length=50)),
                ('NID', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(code='1', message='Please enter a valid national ID', regex='^.{10}$')])),
                ('BDate', models.DateField()),
                ('sex', models.CharField(max_length=1, validators=[django.core.validators.RegexValidator(code='2', message='incorrect gender', regex='^.{1}$')])),
                ('phone', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='3', message='Please enter a valid number', regex='^.{10}$')])),
                ('hasAcc', models.BooleanField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
