# Generated by Django 2.2.4 on 2019-08-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('Auth', '0002_auto_20190826_1906'),
    ]

 
