# Generated by Django 2.2.4 on 2019-08-21 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_account_isadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='BDate',
        ),
        migrations.RemoveField(
            model_name='account',
            name='sex',
        ),
    ]
