# Generated by Django 2.2.4 on 2019-08-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_auto_20190821_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='isAdmin',
            new_name='is_staff',
        ),
    ]
