# Generated by Django 2.2.4 on 2019-08-22 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='driver',
            fields=[
                ('fullname', models.CharField(max_length=50)),
                ('NID', models.IntegerField(validators=[django.core.validators.MinValueValidator(1000000000, django.core.validators.MaxValueValidator(9999999999))])),
                ('licenseNo', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)])),
                ('issueDate', models.DateField()),
                ('expDate', models.DateField()),
                ('center', models.CharField(max_length=10)),
                ('ltype', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='car',
            fields=[
                ('tarmeez', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
                ('Num', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99999)])),
                ('owner', models.CharField(max_length=40)),
                ('cmake', models.CharField(max_length=15)),
                ('use', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20)),
                ('yearModel', models.IntegerField(validators=[django.core.validators.MaxValueValidator(2019), django.core.validators.MinValueValidator(1990)])),
                ('reg_no', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)])),
                ('chassis', models.CharField(max_length=17, unique=True)),
                ('car_id', models.CharField(max_length=8)),
                ('licenseExp', models.DateField()),
                ('passengers', models.IntegerField()),
                ('insuranceC', models.CharField(max_length=15)),
                ('insuranceP', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)])),
            ],
            options={
                'unique_together': {('tarmeez', 'Num')},
            },
        ),
    ]
