# Generated by Django 2.2.4 on 2019-08-22 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0004_auto_20190822_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_id',
        ),
    ]
