# Generated by Django 2.2.4 on 2019-08-22 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0005_remove_car_car_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='renew',
            field=models.BooleanField(default=False),
        ),
    ]
