# Generated by Django 2.2.4 on 2019-08-24 05:29

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0006_auto_20190824_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='expDate',
            field=models.DateField(default=datetime.date(2015, 11, 23)),
        ),
        migrations.AlterField(
            model_name='driver',
            name='issueDate',
            field=models.DateField(verbose_name=datetime.date(2015, 6, 18)),
        ),
        migrations.AlterField(
            model_name='driver',
            name='licenseNo',
            field=models.IntegerField(default=50066211, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
