# Generated by Django 2.2.4 on 2019-08-26 20:50

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0006_auto_20190826_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='expDate',
            field=models.DateField(default=datetime.date(2016, 11, 12)),
        ),
        migrations.AlterField(
            model_name='driver',
            name='issueDate',
            field=models.DateField(verbose_name=datetime.date(2007, 3, 11)),
        ),
        migrations.AlterField(
            model_name='driver',
            name='licenseNo',
            field=models.IntegerField(default=55761418, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)]),
        ),
    ]
