# Generated by Django 2.2.4 on 2019-08-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0006_car_renew'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='renew',
            field=models.BooleanField(default=False),
        ),
    ]
